apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-manager-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-manager-mongo
  template:
    metadata:
      labels:
        app: agent-manager-mongo
    spec:
      containers:
      - name: agent-manager-mongo
        image: mongo:7.0
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: agent-manager-mongo-storage
          mountPath: /data/db
      volumes:
      - name: agent-manager-mongo-storage
        persistentVolumeClaim:
          claimName: agent-manager-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: agent-manager-mongo-srv
spec:
  selector:
    app: agent-manager-mongo
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-manager-mongo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

