apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-learning-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-learning
  template:
    metadata:
      labels:
        app: agent-learning
    spec:
      containers:
        - name: agent-learning
          image: bahmansalehinic4/agent-learning
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: KAFKA_BROKER_URL
              value: 'redpanda-srv:9092'
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://agent-learning-mongo-srv:27017/agent-learning"
            - name: JWT_DEV
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_DEV
            - name: REDIS_HOST
              value: "agent-learning-redis-srv"
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: agent-learning-srv
spec:
  selector:
    app: agent-learning
  ports:
    - name: agent-learning
      protocol: TCP
      port: 3000
      targetPort: 3000

