apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-gateway-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-gateway-mongo
  template:
    metadata:
      labels:
        app: ai-gateway-mongo
    spec:
      containers:
        - name: ai-gateway-mongo
          image: mongo:7.0
          ports:
            - name: mongo
              containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: ai-gateway-mongo-srv
spec:
  selector:
    app: ai-gateway-mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017

