apiVersion: apps/v1
kind: Deployment
metadata:
  name: ar-avatar-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ar-avatar-mongo
  template:
    metadata:
      labels:
        app: ar-avatar-mongo
    spec:
      containers:
        - name: ar-avatar-mongo
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: ar-avatar
          volumeMounts:
            - name: ar-avatar-mongo-storage
              mountPath: /data/db
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
      volumes:
        - name: ar-avatar-mongo-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ar-avatar-mongo-srv
spec:
  selector:
    app: ar-avatar-mongo
  ports:
    - name: mongo
      protocol: TCP
      port: 27017
      targetPort: 27017

