apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-orders-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-orders
  template:
    metadata:
      labels:
        app: ecommerce-orders
    spec:
      containers:
        - name: ecommerce-orders
          image: bahmansalehinic4/ecommerce-orders
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env: 
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: "aichatwar"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
            - name: KAFKA_BROKER_URL
              value: 'redpanda-srv:9092'
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
            - name: MONGO_URI
              value: "mongodb://ecommerce-orders-mongo-srv:27017/ecommerceorders"
            - name: JWT_DEV
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_DEV
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-orders-srv
spec:
  selector:
    app: ecommerce-orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000 