apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback
  template:
    metadata:
      labels:
        app: feedback
    spec:
      containers:
        - name: feedback
          image: bahmansalehinic4/feedback
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: KAFKA_BROKER_URL
              value: 'redpanda-srv:9092'
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://feedback-mongo-srv:27017/feedback"
            - name: JWT_DEV
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_DEV
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-srv
spec:
  selector:
    app: feedback
  ports:
    - name: feedback
      protocol: TCP
      port: 3000
      targetPort: 3000

