apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
        - name: feed
          image: bahmansalehinic4/feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:  
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: "aichatwar"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
            - name: KAFKA_BROKER_URL
              value: 'redpanda-srv:9092'
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
            - name: MONGO_URI
              value: "mongodb://feed-mongo-srv:27017/feed"
            - name: JWT_DEV
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_DEV
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: azure-storage
                  key: AZURE_STORAGE_ACCOUNT
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage
                  key: AZURE_STORAGE_KEY
            # Agent Feed Scanner Configuration
            - name: AGENT_FEED_SCANNER_ENABLED
              value: "true"
            - name: AGENT_FEED_SCAN_INTERVAL_CRON
              value: "0 * * * *"  # Every hour
            - name: TEST_AGENT_FEED_SCAN_INTERVAL_CRON
              value: "*/20 * * * * *"  # Every 20 seconds for testing
            - name: USE_TEST_AGENT_FEED_SCAN_INTERVAL
              value: "true"  # Set to "true" for testing
            - name: MAX_AGENT_FEED_ITEMS_PER_SCAN
              value: "50"
        
        # - name: feed-worker
        #   image: bahmansalehinic4/feed
        #   command: ["npm", "run", "start:worker"]
          # envFrom:
          #   - secretRef:
          #       name: feed-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: feed-srv
spec:
  selector:
    app: feed
  ports:
    - name: feed
      protocol: TCP
      port: 3000
      targetPort: 3000 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-worker-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feed-worker
  template:
    metadata:
      labels:
        app: feed-worker
    spec:
      containers:
        - name: feed-worker
          image: bahmansalehinic4/feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          command: ["npm", "run", "start:worker"]
          env:  
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: "aichatwar"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
            - name: KAFKA_BROKER_URL
              value: 'redpanda-srv:9092'
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            
            - name: MONGO_URI
              value: "mongodb://feed-mongo-srv:27017/feed"
            - name: JWT_DEV
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_DEV
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: AZURE_STORAGE_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: azure-storage
                  key: AZURE_STORAGE_ACCOUNT
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage
                  key: AZURE_STORAGE_KEY

             