apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-learning-mongodb-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-learning-mongodb
  template:
    metadata:
      labels:
        app: feedback-learning-mongodb
    spec:
      containers:
        - name: feedback-learning-mongodb
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: feedback-learning-mongo-srv
spec:
  selector:
    app: feedback-learning-mongodb
  ports:
    - name: feedback-learning-mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017

