apiVersion: apps/v1
kind: Deployment
metadata:
  name: friend-suggestions-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friend-suggestions-mongo
  template:
    metadata:
      labels:
        app: friend-suggestions-mongo
    spec:
      containers:
        - name: friend-suggestions-mongo
          image: mongo:7.0
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: friend-suggestions-mongo-srv
spec:
  selector:
    app: friend-suggestions-mongo
  ports:
    - name: friend-suggestions-mongo
      protocol: TCP
      port: 27017
      targetPort: 27017

