apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-room-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-room
  template:
    metadata:
      labels:
        app: redis-room
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-room-srv
spec:
  selector:
    app: redis-room
  ports:
    - name: redis
      port: 6379
      targetPort: 6379

